
SERVER_OBJS=server.o proj_info.o utils.o buffer.o db_support.o client.o cli_mgr.o basic_mgr.o clientset.o projectmap.o mgr_helper.o
MGR_OBJS=server_mgr.o proj_info.o utils.o buffer.o

CC=g++
LD=g++

CFLAGS=-fno-rtti

#Print error messages
#CFLAGS+=-DDEBUG
#NDEBUG=-D DEBUG

#need the following when using threads
EXTRALIBS=-lpthread -lpq -lcrypto

#use the following to strip your binary
#LDFLAGS+=-s

all: collab collab_mgr

.SUFFIXES   : .h
.PATH.h     : /usr/local/include
.INCLUDES   : .h

.SUFFIXES   : .o .cpp
.cpp.o        :
	$(CC) $(CFLAGS) -c $(.IMPSRC) $(.INCLUDES)

collab: $(SERVER_OBJS)
	$(LD) $(LDFLAGS) -o $(.TARGET) $(.ALLSRC) $(EXTRALIBS) 

collab_mgr: $(MGR_OBJS)
	$(LD) $(LDFLAGS) -o $(.TARGET) $(.ALLSRC) $(EXTRALIBS) 

clean:
	-@rm *.o

